Introduce Polynomial_Vector type which can be used in El::Matrix<Polynomial_Vector>
This is a simple std::vector<Polynomial> with function Zero().

On Expanse HPC, compilation of El::Matrix<std::vector<Polynomial> failed with
error: 'class std::vector<Polynomial>' has no member named 'Zero'

Zero() is (sometimes) called by El::MemZero() when allocating memory to matrix.